# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'Numerosas patas el de <a href="http://mongodbperu.com" target="_blank">MongoDB Perú</a> penosamente delgadas en comparación con el grosor normal de sus dos piernas. hecho por nosotros<a href="https://twitter.com/mdo" target="_blank">@mongodbperu</a>'
url:              http://mongodbperu.com

author:
  name:           'MongoDB Perú'
  url:            https://twitter.com/mongodbperu

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde